name: odc
channels:
- conda-forge
- defaults
- nodefaults
dependencies:
- python >= 3.6
- pyyaml
- sqlalchemy
- python-dateutil
- jsonschema
- cachetools
- cloudpickle >= 0.4.0 # pickle logger objects
- numpy
- rasterio >= 1.0.2  # multi-band reproject bugs got fixed in that version 
- singledispatch
- netcdf4
- psycopg2
- gdal                # [not py27]
- dask
- xarray
- matplotlib # pixel drill app
- sphinx
- sphinx_rtd_theme
- pathos # for s3io/etc
- pip:
    - sphinxcontrib-plantuml
    - sphinx-click
